// src/components/ContextMenu.svelte
<script module lang="ts">
  export interface ContextMenuItem {
    label: string;
    action: () => void | Promise<void>;
    danger?: boolean;
    disabled?: boolean;
    separatorBefore?: boolean;
    shortcut?: string;
  }
</script>

<script lang="ts">
  import { ContextMenu, type ContextMenuTriggerProps } from 'bits-ui';
  import type { Snippet } from 'svelte';

  type TriggerRenderProps = Parameters<NonNullable<ContextMenuTriggerProps['child']>>[0];

  interface Props {
    items: ContextMenuItem[];
    children: Snippet<[TriggerRenderProps]>;
  }

  const { items, children }: Props = $props();
</script>

<ContextMenu.Root>
  <ContextMenu.Trigger>
    {#snippet child({ props })}
      {@render children({ props })}
    {/snippet}
  </ContextMenu.Trigger>
  <ContextMenu.Portal>
    <ContextMenu.Content class="z-[91] grid min-w-[186px] max-w-[min(280px,calc(100vw_-_16px))] w-max rounded-xl border border-line-strong bg-floating p-1.5 shadow-overlay backdrop-blur-xl backdrop-saturate-[115%] [transform-origin:top_left]" collisionPadding={8}>
      {#each items as item}
        {#if item.separatorBefore}<ContextMenu.Separator class="mx-1 my-1 h-px bg-line" />{/if}
        <ContextMenu.Item
          class={`flex min-h-[29px] w-full items-center justify-between gap-5 rounded-md px-2 text-left text-xs whitespace-nowrap text-ink-soft outline-none data-[highlighted]:bg-panel-active data-[highlighted]:text-ink data-[disabled]:opacity-40 ${item.danger ? 'text-[color-mix(in_srgb,var(--danger)_88%,var(--text-soft))] data-[highlighted]:bg-[color-mix(in_srgb,var(--danger)_12%,transparent)]' : ''}`}
          disabled={item.disabled}
          textValue={item.label}
          onSelect={() => void item.action()}
        >
          <span>{item.label}</span>
          {#if item.shortcut}<kbd class="text-[11px] text-faint">{item.shortcut}</kbd>{/if}
        </ContextMenu.Item>
      {/each}
    </ContextMenu.Content>
  </ContextMenu.Portal>
</ContextMenu.Root>

// src/design/ContextMenu.tsx
import type { ReactNode } from "react";
import { ContextMenu as BaseContextMenu } from "@base-ui/react/context-menu";
import { cn } from "./cn";

export type ContextMenuItem = {
  label: string;
  onSelect?: () => void;
  disabled?: boolean;
  tone?: "default" | "danger";
};

type ContextMenuProps = {
  children: ReactNode;
  items: Array<ContextMenuItem | "separator">;
};

/** Native-feeling app menu, shared by every custom right-click surface. */
export function ContextMenu({ children, items }: ContextMenuProps) {
  return (
    <BaseContextMenu.Root>
      <BaseContextMenu.Trigger className="contents">{children}</BaseContextMenu.Trigger>
      <BaseContextMenu.Portal>
        <BaseContextMenu.Positioner sideOffset={6} alignOffset={-4}>
          <BaseContextMenu.Popup
            className={cn(
              "surface-popover z-50 min-w-48 rounded-control border border-line bg-surface p-1 shadow-soft-2",
              "outline-none",
            )}
          >
            {items.map((item, index) =>
              item === "separator" ? (
                <div key={`separator-${index}`} className="my-1 h-px bg-line" role="separator" />
              ) : (
                <BaseContextMenu.Item
                  key={item.label}
                  disabled={item.disabled}
                  onClick={item.onSelect}
                  className={cn(
                    "flex min-h-8 w-full items-center rounded-md px-2.5 py-1.5 text-left text-[13px] font-medium",
                    "text-ink outline-none transition-colors duration-[var(--duration-fast)]",
                    "data-[highlighted]:bg-surface-2 data-[highlighted]:text-ink",
                    "data-[disabled]:cursor-not-allowed data-[disabled]:text-ink-3",
                    item.tone === "danger" && "text-clay data-[highlighted]:bg-clay-tint data-[highlighted]:text-clay",
                  )}
                >
                  {item.label}
                </BaseContextMenu.Item>
              ),
            )}
          </BaseContextMenu.Popup>
        </BaseContextMenu.Positioner>
      </BaseContextMenu.Portal>
    </BaseContextMenu.Root>
  );
}
